[package]
name = "solana-liq-pool-client"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-client = "1.18.9"
solana-sdk = "1.18.9"
solana-program = "1.18.9"
borsh = "0.10.3"
borsh-derive = "0.10.3"
anyhow = "1.0.86"
shellexpand = "2.1"
spl-token = "6.0.0"
serde_json = "1.0"
